[cache]
dir = ".cache"
package = "winpassage"
redirect_cargo_home = false
redirect_gradle = false

[cargo]
target_dir = "rust/packages/{package}/target"

[env]
NPM_CONFIG_CACHE = "js/npm"
AUBE_STORE_PATH = "js/aube-store"
YARN_CACHE_FOLDER = "js/yarn"
